### ISSUE TITLE
Class 'guzzlehttp\Client' not found 

### ISSUE THREAD

**Issue by mohhamedion** [zhooravell/skrill-php-client#4]
i install the app with composer !

i include the code that you put 
and i get this!

Fatal error: Uncaught Error: Class 'guzzlehttp\Client' not found in C:\xampp\htdocs\skrill2\index.php:13 Stack trace: #0 {main} thrown in C:\xampp\htdocs\skrill2\index.php on line 13

**Comment by zhooravell** [comment]
skrill-php-client it is not app. It is a library. You need to configure it. I need more information to help you. You may have forgotten to add 'require_once "vendor/bootstrap.php";'

**Comment by zhooravell** [comment]
@mohhamedion, can i close issues? or you still need help?
