### ISSUE TITLE
Consider adding .gitattributes

### ISSUE THREAD

**Issue by peter279k** [zhooravell/skrill-php-client#9]
As title, it should be nice to add this file for this and other PHP packages.

Why? Because PHP developers don't need the PHP package test stuffs on production.

Once using this file, it will ignore specific file and folders during `composer require user_name/package_name` command running.

Here are some useful references about using `.gitattributes` file:

- https://medium.com/@pablorsk/be-a-git-ninja-the-gitattributes-file-e58c07c9e915
- https://madewithlove.com/gitattributes/
- https://www.reddit.com/r/PHP/comments/2jzp6k/i_dont_need_your_tests_in_my_production/

Once this issue is accepted by @zhooravell, I will be happy to work on this :smiley:.

**Comment by mifzp-dev** [comment]
Good idea! [Here ](https://github.com/zhooravell/skrill-php-client/pull/12)request.

**Comment by peter279k** [comment]
Thanks :).

**Comment by peter279k** [comment]
Closed via https://github.com/zhooravell/skrill-php-client/pull/12
